// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5FkPEaxs7FcAXCZv0QM1eGG4NlhA94mU',
    appId: '1:153846120403:web:49779e440c8c189ed27926',
    messagingSenderId: '153846120403',
    projectId: 'pfaa-9a614',
    authDomain: 'pfaa-9a614.firebaseapp.com',
    databaseURL: 'https://pfaa-9a614-default-rtdb.firebaseio.com',
    storageBucket: 'pfaa-9a614.firebasestorage.app',
    measurementId: 'G-8EXTQ5TL3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLcGvH5fdq6D5pJ1s0lpVro6uaLbMOBKg',
    appId: '1:153846120403:android:c4adc1b21245e9f8d27926',
    messagingSenderId: '153846120403',
    projectId: 'pfaa-9a614',
    databaseURL: 'https://pfaa-9a614-default-rtdb.firebaseio.com',
    storageBucket: 'pfaa-9a614.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBSnuuYG1jT3PYEGA7qgF6EH-USRFkzac',
    appId: '1:153846120403:ios:55f78d92be9b155cd27926',
    messagingSenderId: '153846120403',
    projectId: 'pfaa-9a614',
    databaseURL: 'https://pfaa-9a614-default-rtdb.firebaseio.com',
    storageBucket: 'pfaa-9a614.firebasestorage.app',
    iosBundleId: 'com.example.vroomlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBSnuuYG1jT3PYEGA7qgF6EH-USRFkzac',
    appId: '1:153846120403:ios:55f78d92be9b155cd27926',
    messagingSenderId: '153846120403',
    projectId: 'pfaa-9a614',
    databaseURL: 'https://pfaa-9a614-default-rtdb.firebaseio.com',
    storageBucket: 'pfaa-9a614.firebasestorage.app',
    iosBundleId: 'com.example.vroomlog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5FkPEaxs7FcAXCZv0QM1eGG4NlhA94mU',
    appId: '1:153846120403:web:6fafba2e01afaaafd27926',
    messagingSenderId: '153846120403',
    projectId: 'pfaa-9a614',
    authDomain: 'pfaa-9a614.firebaseapp.com',
    databaseURL: 'https://pfaa-9a614-default-rtdb.firebaseio.com',
    storageBucket: 'pfaa-9a614.firebasestorage.app',
    measurementId: 'G-YB8C3EGK71',
  );
}
